import { useState, useEffect } from 'react';
import { SafeAreaView, StyleSheet, Text, Image, Dimensions, Animated, TouchableOpacity } from 'react-native';
import { useIsFocused } from '@react-navigation/native';
import Constants from 'expo-constants';
import { SimpleLineIcons } from '@expo/vector-icons';
import { useOrientation } from '../data/orientation';
import AsyncStorage from '@react-native-async-storage/async-storage';

const HEADER_HEIGHT = 75 + Constants.statusBarHeight;
const scrollAnim = new Animated.Value(0);
const clampedScrollY = scrollAnim.interpolate({
  inputRange: [HEADER_HEIGHT, HEADER_HEIGHT + 1],
  outputRange: [0, 1],
  extrapolateLeft: 'clamp',
});
const minusScrollY = Animated.multiply(clampedScrollY, -1);
const translateY = Animated.diffClamp(minusScrollY, -HEADER_HEIGHT, 0);

const win = Dimensions.get('screen');
const ratio = win.width/875;

export default function FullQuran({ route, navigation }) {
  const orientation = useOrientation();
  const isFocused = useIsFocused();
  const [listReady, setListReady] = useState(false);
  const [scrollIndex,setScrollIndex] = useState(0);
  const [IsEng, setIsEng] = useState(0);
  const [ref,setRef] = useState(null);
  const handleScroll = (event) => {
    let yOffset = Math.floor(event.nativeEvent.contentOffset.y/picHeight);
    setScrollIndex(yOffset);
  };
  const [imageWide, setImageWide] = useState(0);

  useEffect(() => {
    if (isFocused && listReady) {
      if(route.params){
        const callback = (page) => ref.scrollToIndex({ animated: false, index: page });
        if(route.params.page > 0){
          callback(route.params.page);
          navigation.setParams({ page: 0 });
        }
      }
    }
  },[isFocused,route,ref,navigation]);
  
  useEffect(() => {
    if(isFocused){
      const restoreValue = async () => {
          await AsyncStorage.getItem("imageWide").then((value)=>{
            if(value != null) setImageWide(parseInt(value))
          });
          await AsyncStorage.getItem("LangIsEng").then((value)=>{
            if(value != null) setIsEng(parseInt(value))
          });
      };
      restoreValue();
    }
  }, [isFocused,AsyncStorage, setImageWide, setIsEng]);
  const languageJson = require("../data/language.json");
  const [images, setImages] = useState([
    require("../data/pics/page1.jpg"),
    require("../data/pics/page2.jpg"),
    require("../data/pics/page3.jpg"),
    require("../data/pics/page4.jpg"),
    require("../data/pics/page5.jpg"),
    require("../data/pics/page6.jpg"),
    require("../data/pics/page7.jpg"),
    require("../data/pics/page8.jpg"),
    require("../data/pics/page9.jpg"),
    require("../data/pics/page10.jpg"),
    require("../data/pics/page11.jpg"),
    require("../data/pics/page12.jpg"),
    require("../data/pics/page13.jpg"),
    require("../data/pics/page14.jpg"),
    require("../data/pics/page15.jpg"),
    require("../data/pics/page16.jpg"),
    require("../data/pics/page17.jpg"),
    require("../data/pics/page18.jpg"),
    require("../data/pics/page19.jpg"),
    require("../data/pics/page20.jpg"),
    require("../data/pics/page21.jpg"),
    require("../data/pics/page22.jpg"),
    require("../data/pics/page23.jpg"),
    require("../data/pics/page24.jpg"),
    require("../data/pics/page25.jpg"),
    require("../data/pics/page26.jpg"),
    require("../data/pics/page27.jpg"),
    require("../data/pics/page28.jpg"),
    require("../data/pics/page29.jpg"),
    require("../data/pics/page30.jpg"),
    require("../data/pics/page31.jpg"),
    require("../data/pics/page32.jpg"),
    require("../data/pics/page33.jpg"),
    require("../data/pics/page34.jpg"),
    require("../data/pics/page35.jpg"),
    require("../data/pics/page36.jpg"),
    require("../data/pics/page37.jpg"),
    require("../data/pics/page38.jpg"),
    require("../data/pics/page39.jpg"),
    require("../data/pics/page40.jpg"),
    require("../data/pics/page41.jpg"),
    require("../data/pics/page42.jpg"),
    require("../data/pics/page43.jpg"),
    require("../data/pics/page44.jpg"),
    require("../data/pics/page45.jpg"),
    require("../data/pics/page46.jpg"),
    require("../data/pics/page47.jpg"),
    require("../data/pics/page48.jpg"),
    require("../data/pics/page49.jpg"),
    require("../data/pics/page50.jpg"),
    require("../data/pics/page51.jpg"),
    require("../data/pics/page52.jpg"),
    require("../data/pics/page53.jpg"),
    require("../data/pics/page54.jpg"),
    require("../data/pics/page55.jpg"),
    require("../data/pics/page56.jpg"),
    require("../data/pics/page57.jpg"),
    require("../data/pics/page58.jpg"),
    require("../data/pics/page59.jpg"),
    require("../data/pics/page60.jpg"),
    require("../data/pics/page61.jpg"),
    require("../data/pics/page62.jpg"),
    require("../data/pics/page63.jpg"),
    require("../data/pics/page64.jpg"),
    require("../data/pics/page65.jpg"),
    require("../data/pics/page66.jpg"),
    require("../data/pics/page67.jpg"),
    require("../data/pics/page68.jpg"),
    require("../data/pics/page69.jpg"),
    require("../data/pics/page70.jpg"),
    require("../data/pics/page71.jpg"),
    require("../data/pics/page72.jpg"),
    require("../data/pics/page73.jpg"),
    require("../data/pics/page74.jpg"),
    require("../data/pics/page75.jpg"),
    require("../data/pics/page76.jpg"),
    require("../data/pics/page77.jpg"),
    require("../data/pics/page78.jpg"),
    require("../data/pics/page79.jpg"),
    require("../data/pics/page80.jpg"),
    require("../data/pics/page81.jpg"),
    require("../data/pics/page82.jpg"),
    require("../data/pics/page83.jpg"),
    require("../data/pics/page84.jpg"),
    require("../data/pics/page85.jpg"),
    require("../data/pics/page86.jpg"),
    require("../data/pics/page87.jpg"),
    require("../data/pics/page88.jpg"),
    require("../data/pics/page89.jpg"),
    require("../data/pics/page90.jpg"),
    require("../data/pics/page91.jpg"),
    require("../data/pics/page92.jpg"),
    require("../data/pics/page93.jpg"),
    require("../data/pics/page94.jpg"),
    require("../data/pics/page95.jpg"),
    require("../data/pics/page96.jpg"),
    require("../data/pics/page97.jpg"),
    require("../data/pics/page98.jpg"),
    require("../data/pics/page99.jpg"),
    require("../data/pics/page100.jpg"),
    require("../data/pics/page101.jpg"),
    require("../data/pics/page102.jpg"),
    require("../data/pics/page103.jpg"),
    require("../data/pics/page104.jpg"),
    require("../data/pics/page105.jpg"),
    require("../data/pics/page106.jpg"),
    require("../data/pics/page107.jpg"),
    require("../data/pics/page108.jpg"),
    require("../data/pics/page109.jpg"),
    require("../data/pics/page110.jpg"),
    require("../data/pics/page111.jpg"),
    require("../data/pics/page112.jpg"),
    require("../data/pics/page113.jpg"),
    require("../data/pics/page114.jpg"),
    require("../data/pics/page115.jpg"),
    require("../data/pics/page116.jpg"),
    require("../data/pics/page117.jpg"),
    require("../data/pics/page118.jpg"),
    require("../data/pics/page119.jpg"),
    require("../data/pics/page120.jpg"),
    require("../data/pics/page121.jpg"),
    require("../data/pics/page122.jpg"),
    require("../data/pics/page123.jpg"),
    require("../data/pics/page124.jpg"),
    require("../data/pics/page125.jpg"),
    require("../data/pics/page126.jpg"),
    require("../data/pics/page127.jpg"),
    require("../data/pics/page128.jpg"),
    require("../data/pics/page129.jpg"),
    require("../data/pics/page130.jpg"),
    require("../data/pics/page131.jpg"),
    require("../data/pics/page132.jpg"),
    require("../data/pics/page133.jpg"),
    require("../data/pics/page134.jpg"),
    require("../data/pics/page135.jpg"),
    require("../data/pics/page136.jpg"),
    require("../data/pics/page137.jpg"),
    require("../data/pics/page138.jpg"),
    require("../data/pics/page139.jpg"),
    require("../data/pics/page140.jpg"),
    require("../data/pics/page141.jpg"),
    require("../data/pics/page142.jpg"),
    require("../data/pics/page143.jpg"),
    require("../data/pics/page144.jpg"),
    require("../data/pics/page145.jpg"),
    require("../data/pics/page146.jpg"),
    require("../data/pics/page147.jpg"),
    require("../data/pics/page148.jpg"),
    require("../data/pics/page149.jpg"),
    require("../data/pics/page150.jpg"),
    require("../data/pics/page151.jpg"),
    require("../data/pics/page152.jpg"),
    require("../data/pics/page153.jpg"),
    require("../data/pics/page154.jpg"),
    require("../data/pics/page155.jpg"),
    require("../data/pics/page156.jpg"),
    require("../data/pics/page157.jpg"),
    require("../data/pics/page158.jpg"),
    require("../data/pics/page159.jpg"),
    require("../data/pics/page160.jpg"),
    require("../data/pics/page161.jpg"),
    require("../data/pics/page162.jpg"),
    require("../data/pics/page163.jpg"),
    require("../data/pics/page164.jpg"),
    require("../data/pics/page165.jpg"),
    require("../data/pics/page166.jpg"),
    require("../data/pics/page167.jpg"),
    require("../data/pics/page168.jpg"),
    require("../data/pics/page169.jpg"),
    require("../data/pics/page170.jpg"),
    require("../data/pics/page171.jpg"),
    require("../data/pics/page172.jpg"),
    require("../data/pics/page173.jpg"),
    require("../data/pics/page174.jpg"),
    require("../data/pics/page175.jpg"),
    require("../data/pics/page176.jpg"),
    require("../data/pics/page177.jpg"),
    require("../data/pics/page178.jpg"),
    require("../data/pics/page179.jpg"),
    require("../data/pics/page180.jpg"),
    require("../data/pics/page181.jpg"),
    require("../data/pics/page182.jpg"),
    require("../data/pics/page183.jpg"),
    require("../data/pics/page184.jpg"),
    require("../data/pics/page185.jpg"),
    require("../data/pics/page186.jpg"),
    require("../data/pics/page187.jpg"),
    require("../data/pics/page188.jpg"),
    require("../data/pics/page189.jpg"),
    require("../data/pics/page190.jpg"),
    require("../data/pics/page191.jpg"),
    require("../data/pics/page192.jpg"),
    require("../data/pics/page193.jpg"),
    require("../data/pics/page194.jpg"),
    require("../data/pics/page195.jpg"),
    require("../data/pics/page196.jpg"),
    require("../data/pics/page197.jpg"),
    require("../data/pics/page198.jpg"),
    require("../data/pics/page199.jpg"),
    require("../data/pics/page200.jpg"),
    require("../data/pics/page201.jpg"),
    require("../data/pics/page202.jpg"),
    require("../data/pics/page203.jpg"),
    require("../data/pics/page204.jpg"),
    require("../data/pics/page205.jpg"),
    require("../data/pics/page206.jpg"),
    require("../data/pics/page207.jpg"),
    require("../data/pics/page208.jpg"),
    require("../data/pics/page209.jpg"),
    require("../data/pics/page210.jpg"),
    require("../data/pics/page211.jpg"),
    require("../data/pics/page212.jpg"),
    require("../data/pics/page213.jpg"),
    require("../data/pics/page214.jpg"),
    require("../data/pics/page215.jpg"),
    require("../data/pics/page216.jpg"),
    require("../data/pics/page217.jpg"),
    require("../data/pics/page218.jpg"),
    require("../data/pics/page219.jpg"),
    require("../data/pics/page220.jpg"),
    require("../data/pics/page221.jpg"),
    require("../data/pics/page222.jpg"),
    require("../data/pics/page223.jpg"),
    require("../data/pics/page224.jpg"),
    require("../data/pics/page225.jpg"),
    require("../data/pics/page226.jpg"),
    require("../data/pics/page227.jpg"),
    require("../data/pics/page228.jpg"),
    require("../data/pics/page229.jpg"),
    require("../data/pics/page230.jpg"),
    require("../data/pics/page231.jpg"),
    require("../data/pics/page232.jpg"),
    require("../data/pics/page233.jpg"),
    require("../data/pics/page234.jpg"),
    require("../data/pics/page235.jpg"),
    require("../data/pics/page236.jpg"),
    require("../data/pics/page237.jpg"),
    require("../data/pics/page238.jpg"),
    require("../data/pics/page239.jpg"),
    require("../data/pics/page240.jpg"),
    require("../data/pics/page241.jpg"),
    require("../data/pics/page242.jpg"),
    require("../data/pics/page243.jpg"),
    require("../data/pics/page244.jpg"),
    require("../data/pics/page245.jpg"),
    require("../data/pics/page246.jpg"),
    require("../data/pics/page247.jpg"),
    require("../data/pics/page248.jpg"),
    require("../data/pics/page249.jpg"),
    require("../data/pics/page250.jpg"),
    require("../data/pics/page251.jpg"),
    require("../data/pics/page252.jpg"),
    require("../data/pics/page253.jpg"),
    require("../data/pics/page254.jpg"),
    require("../data/pics/page255.jpg"),
    require("../data/pics/page256.jpg"),
    require("../data/pics/page257.jpg"),
    require("../data/pics/page258.jpg"),
    require("../data/pics/page259.jpg"),
    require("../data/pics/page260.jpg"),
    require("../data/pics/page261.jpg"),
    require("../data/pics/page262.jpg"),
    require("../data/pics/page263.jpg"),
    require("../data/pics/page264.jpg"),
    require("../data/pics/page265.jpg"),
    require("../data/pics/page266.jpg"),
    require("../data/pics/page267.jpg"),
    require("../data/pics/page268.jpg"),
    require("../data/pics/page269.jpg"),
    require("../data/pics/page270.jpg"),
    require("../data/pics/page271.jpg"),
    require("../data/pics/page272.jpg"),
    require("../data/pics/page273.jpg"),
    require("../data/pics/page274.jpg"),
    require("../data/pics/page275.jpg"),
    require("../data/pics/page276.jpg"),
    require("../data/pics/page277.jpg"),
    require("../data/pics/page278.jpg"),
    require("../data/pics/page279.jpg"),
    require("../data/pics/page280.jpg"),
    require("../data/pics/page281.jpg"),
    require("../data/pics/page282.jpg"),
    require("../data/pics/page283.jpg"),
    require("../data/pics/page284.jpg"),
    require("../data/pics/page285.jpg"),
    require("../data/pics/page286.jpg"),
    require("../data/pics/page287.jpg"),
    require("../data/pics/page288.jpg"),
    require("../data/pics/page289.jpg"),
    require("../data/pics/page290.jpg"),
    require("../data/pics/page291.jpg"),
    require("../data/pics/page292.jpg"),
    require("../data/pics/page293.jpg"),
    require("../data/pics/page294.jpg"),
    require("../data/pics/page295.jpg"),
    require("../data/pics/page296.jpg"),
    require("../data/pics/page297.jpg"),
    require("../data/pics/page298.jpg"),
    require("../data/pics/page299.jpg"),
    require("../data/pics/page300.jpg"),
    require("../data/pics/page301.jpg"),
    require("../data/pics/page302.jpg"),
    require("../data/pics/page303.jpg"),
    require("../data/pics/page304.jpg"),
    require("../data/pics/page305.jpg"),
    require("../data/pics/page306.jpg"),
    require("../data/pics/page307.jpg"),
    require("../data/pics/page308.jpg"),
    require("../data/pics/page309.jpg"),
    require("../data/pics/page310.jpg"),
    require("../data/pics/page311.jpg"),
    require("../data/pics/page312.jpg"),
    require("../data/pics/page313.jpg"),
    require("../data/pics/page314.jpg"),
    require("../data/pics/page315.jpg"),
    require("../data/pics/page316.jpg"),
    require("../data/pics/page317.jpg"),
    require("../data/pics/page318.jpg"),
    require("../data/pics/page319.jpg"),
    require("../data/pics/page320.jpg"),
    require("../data/pics/page321.jpg"),
    require("../data/pics/page322.jpg"),
    require("../data/pics/page323.jpg"),
    require("../data/pics/page324.jpg"),
    require("../data/pics/page325.jpg"),
    require("../data/pics/page326.jpg"),
    require("../data/pics/page327.jpg"),
    require("../data/pics/page328.jpg"),
    require("../data/pics/page329.jpg"),
    require("../data/pics/page330.jpg"),
    require("../data/pics/page331.jpg"),
    require("../data/pics/page332.jpg"),
    require("../data/pics/page333.jpg"),
    require("../data/pics/page334.jpg"),
    require("../data/pics/page335.jpg"),
    require("../data/pics/page336.jpg"),
    require("../data/pics/page337.jpg"),
    require("../data/pics/page338.jpg"),
    require("../data/pics/page339.jpg"),
    require("../data/pics/page340.jpg"),
    require("../data/pics/page341.jpg"),
    require("../data/pics/page342.jpg"),
    require("../data/pics/page343.jpg"),
    require("../data/pics/page344.jpg"),
    require("../data/pics/page345.jpg"),
    require("../data/pics/page346.jpg"),
    require("../data/pics/page347.jpg"),
    require("../data/pics/page348.jpg"),
    require("../data/pics/page349.jpg"),
    require("../data/pics/page350.jpg"),
    require("../data/pics/page351.jpg"),
    require("../data/pics/page352.jpg"),
    require("../data/pics/page353.jpg"),
    require("../data/pics/page354.jpg"),
    require("../data/pics/page355.jpg"),
    require("../data/pics/page356.jpg"),
    require("../data/pics/page357.jpg"),
    require("../data/pics/page358.jpg"),
    require("../data/pics/page359.jpg"),
    require("../data/pics/page360.jpg"),
    require("../data/pics/page361.jpg"),
    require("../data/pics/page362.jpg"),
    require("../data/pics/page363.jpg"),
    require("../data/pics/page364.jpg"),
    require("../data/pics/page365.jpg"),
    require("../data/pics/page366.jpg"),
    require("../data/pics/page367.jpg"),
    require("../data/pics/page368.jpg"),
    require("../data/pics/page369.jpg"),
    require("../data/pics/page370.jpg"),
    require("../data/pics/page371.jpg"),
    require("../data/pics/page372.jpg"),
    require("../data/pics/page373.jpg"),
    require("../data/pics/page374.jpg"),
    require("../data/pics/page375.jpg"),
    require("../data/pics/page376.jpg"),
    require("../data/pics/page377.jpg"),
    require("../data/pics/page378.jpg"),
    require("../data/pics/page379.jpg"),
    require("../data/pics/page380.jpg"),
    require("../data/pics/page381.jpg"),
    require("../data/pics/page382.jpg"),
    require("../data/pics/page383.jpg"),
    require("../data/pics/page384.jpg"),
    require("../data/pics/page385.jpg"),
    require("../data/pics/page386.jpg"),
    require("../data/pics/page387.jpg"),
    require("../data/pics/page388.jpg"),
    require("../data/pics/page389.jpg"),
    require("../data/pics/page390.jpg"),
    require("../data/pics/page391.jpg"),
    require("../data/pics/page392.jpg"),
    require("../data/pics/page393.jpg"),
    require("../data/pics/page394.jpg"),
    require("../data/pics/page395.jpg"),
    require("../data/pics/page396.jpg"),
    require("../data/pics/page397.jpg"),
    require("../data/pics/page398.jpg"),
    require("../data/pics/page399.jpg"),
    require("../data/pics/page400.jpg"),
    require("../data/pics/page401.jpg"),
    require("../data/pics/page402.jpg"),
    require("../data/pics/page403.jpg"),
    require("../data/pics/page404.jpg"),
    require("../data/pics/page405.jpg"),
    require("../data/pics/page406.jpg"),
    require("../data/pics/page407.jpg"),
    require("../data/pics/page408.jpg"),
    require("../data/pics/page409.jpg"),
    require("../data/pics/page410.jpg"),
    require("../data/pics/page411.jpg"),
    require("../data/pics/page412.jpg"),
    require("../data/pics/page413.jpg"),
    require("../data/pics/page414.jpg"),
    require("../data/pics/page415.jpg"),
    require("../data/pics/page416.jpg"),
    require("../data/pics/page417.jpg"),
    require("../data/pics/page418.jpg"),
    require("../data/pics/page419.jpg"),
    require("../data/pics/page420.jpg"),
    require("../data/pics/page421.jpg"),
    require("../data/pics/page422.jpg"),
    require("../data/pics/page423.jpg"),
    require("../data/pics/page424.jpg"),
    require("../data/pics/page425.jpg"),
    require("../data/pics/page426.jpg"),
    require("../data/pics/page427.jpg"),
    require("../data/pics/page428.jpg"),
    require("../data/pics/page429.jpg"),
    require("../data/pics/page430.jpg"),
    require("../data/pics/page431.jpg"),
    require("../data/pics/page432.jpg"),
    require("../data/pics/page433.jpg"),
    require("../data/pics/page434.jpg"),
    require("../data/pics/page435.jpg"),
    require("../data/pics/page436.jpg"),
    require("../data/pics/page437.jpg"),
    require("../data/pics/page438.jpg"),
    require("../data/pics/page439.jpg"),
    require("../data/pics/page440.jpg"),
    require("../data/pics/page441.jpg"),
    require("../data/pics/page442.jpg"),
    require("../data/pics/page443.jpg"),
    require("../data/pics/page444.jpg"),
    require("../data/pics/page445.jpg"),
    require("../data/pics/page446.jpg"),
    require("../data/pics/page447.jpg"),
    require("../data/pics/page448.jpg"),
    require("../data/pics/page449.jpg"),
    require("../data/pics/page450.jpg"),
    require("../data/pics/page451.jpg"),
    require("../data/pics/page452.jpg"),
    require("../data/pics/page453.jpg"),
    require("../data/pics/page454.jpg"),
    require("../data/pics/page455.jpg"),
    require("../data/pics/page456.jpg"),
    require("../data/pics/page457.jpg"),
    require("../data/pics/page458.jpg"),
    require("../data/pics/page459.jpg"),
    require("../data/pics/page460.jpg"),
    require("../data/pics/page461.jpg"),
    require("../data/pics/page462.jpg"),
    require("../data/pics/page463.jpg"),
    require("../data/pics/page464.jpg"),
    require("../data/pics/page465.jpg"),
    require("../data/pics/page466.jpg"),
    require("../data/pics/page467.jpg"),
    require("../data/pics/page468.jpg"),
    require("../data/pics/page469.jpg"),
    require("../data/pics/page470.jpg"),
    require("../data/pics/page471.jpg"),
    require("../data/pics/page472.jpg"),
    require("../data/pics/page473.jpg"),
    require("../data/pics/page474.jpg"),
    require("../data/pics/page475.jpg"),
    require("../data/pics/page476.jpg"),
    require("../data/pics/page477.jpg"),
    require("../data/pics/page478.jpg"),
    require("../data/pics/page479.jpg"),
    require("../data/pics/page480.jpg"),
    require("../data/pics/page481.jpg"),
    require("../data/pics/page482.jpg"),
    require("../data/pics/page483.jpg"),
    require("../data/pics/page484.jpg"),
    require("../data/pics/page485.jpg"),
    require("../data/pics/page486.jpg"),
    require("../data/pics/page487.jpg"),
    require("../data/pics/page488.jpg"),
    require("../data/pics/page489.jpg"),
    require("../data/pics/page490.jpg"),
    require("../data/pics/page491.jpg"),
    require("../data/pics/page492.jpg"),
    require("../data/pics/page493.jpg"),
    require("../data/pics/page494.jpg"),
    require("../data/pics/page495.jpg"),
    require("../data/pics/page496.jpg"),
    require("../data/pics/page497.jpg"),
    require("../data/pics/page498.jpg"),
    require("../data/pics/page499.jpg"),
    require("../data/pics/page500.jpg"),
    require("../data/pics/page501.jpg"),
    require("../data/pics/page502.jpg"),
    require("../data/pics/page503.jpg"),
    require("../data/pics/page504.jpg"),
    require("../data/pics/page505.jpg"),
    require("../data/pics/page506.jpg"),
    require("../data/pics/page507.jpg"),
    require("../data/pics/page508.jpg"),
    require("../data/pics/page509.jpg"),
    require("../data/pics/page510.jpg"),
    require("../data/pics/page511.jpg"),
    require("../data/pics/page512.jpg"),
    require("../data/pics/page513.jpg"),
    require("../data/pics/page514.jpg"),
    require("../data/pics/page515.jpg"),
    require("../data/pics/page516.jpg"),
    require("../data/pics/page517.jpg"),
    require("../data/pics/page518.jpg"),
    require("../data/pics/page519.jpg"),
    require("../data/pics/page520.jpg"),
    require("../data/pics/page521.jpg"),
    require("../data/pics/page522.jpg"),
    require("../data/pics/page523.jpg"),
    require("../data/pics/page524.jpg"),
    require("../data/pics/page525.jpg"),
    require("../data/pics/page526.jpg"),
    require("../data/pics/page527.jpg")
  ]);
  
  const imageHeights = {
    "PORTRAIT":{
      "normal" : 1385 * ratio-25,
      "wide" : win.height-HEADER_HEIGHT
    },
    "LANDSCAPE":{
      "normal" : (1385 * ratio-25)*(win.height-100)/(win.width)-10,
      "wide" : (win.height-HEADER_HEIGHT)*(win.height-100)/(win.width*98/100)-10
    }
  };
const imageWidths = {
  "PORTRAIT":{
    "normal" : win.width, 
    "wide" : win.width*98/100
  },
  "LANDSCAPE":{
    "normal" : win.height-100,
    "wide" : win.height-Constants.statusBarHeight*3
  }
};
  const type = (imageWide==1) ? "wide" : "normal";
  const picHeight = imageHeights[orientation][type];
  const picWidth = imageWidths[orientation][type];
  return (
    <SafeAreaView style={styles.container}>
      <Animated.FlatList
        initialNumToRender={100}
        data={images}
        ref={(ref) => {
          setRef(ref);
          setListReady(true);
        }}
        getItemLayout={(data, index) => ({
          length: picHeight +2,
          offset: (picHeight +2) * index,
          index,
        })}
        initialScrollIndex={0}
        scrollEventThrottle={1}
        bounces={false}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        onScroll={Animated.event(
          [{ nativeEvent: { contentOffset: { y: scrollAnim } } }],
          { useNativeDriver: true,
          listener: event => handleScroll(event) 
        }
        )}
        overScrollMode="never"
        contentInset={{ top: HEADER_HEIGHT }}
        contentOffset={{ y: -HEADER_HEIGHT }}
        renderItem={({ item, index }) => (
          <Image source={item} key={index} style={{
            resizeMode: 'stretch',
            width: picWidth,
            height: picHeight,
            borderWidth: 1,
            borderColor: 'black',
            marginTop: index == 0 ? HEADER_HEIGHT : 0,
            marginLeft: win.width/100,
          }} />
        )}
      />
      <Animated.View style={[styles.header,{
            backgroundColor: "#EFCE8E"
          }, { transform: [{ translateY }] }]}>
        <TouchableOpacity style={{ flexDirection:'row'}} onPress={() => navigation.toggleDrawer()}>
          <SimpleLineIcons name="book-open" size={26} color="black" />
          <Text style={styles.headerText}>{languageJson[IsEng]["screens"][0]}</Text>
        </TouchableOpacity>
      </Animated.View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ecf0f1'
  },
  header: {
    flex: 1,
    height: HEADER_HEIGHT,
    paddingTop: Constants.statusBarHeight,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0
  },
  headerText: {
    color: 'black',
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingHorizontal: 15
  }
});
